mit-pdos/noria

Cargo.toml
benchmarks/piazza/piazza.rs
src/flow/domain/local.rs
src/flow/domain/mod.rs
src/flow/migrate/materialization.rs
src/lib.rs

Benchmark for Piazza application.
This measures two types of benchmak ```migration``` and ```write```.
```migration``` fills the db with users, classes, posts and relations between users and classes (```taking``` base node). Then, it times how long it takes to login a user. Each user login corresponds to one migration that creates a "parallel universe" for that user.
```write``` prepopulates the db similarly. Then, it logs some users and it measures the time it takes to perform a batch of writes. 
There are two important configurations in this benchmark ```dcfg``` and ```fanout```.  ```dcfg``` specifies the domain configuration of the graph, either a single domain or a domain per user. ```fanout``` specifies the fanout of a write passing through the ```taking``` base node (how many …

Add piazza benchmark

---

benchmarks/hotsoup/query_blacklist.txt
src/sql/mir.rs

Reorder filters above aggregations that aggregate over common columns. This allow us to remove some hotcrap queries from the blacklist.

Filter reordering

---

src/mir/mod.rs
src/mir/optimize.rs
src/sql/mir.rs
src/sql/mod.rs

Moving filter merge after reuse allows for more reuse opportunities for filters. Nodes in a chain are filter nodes that:
- have a single ancestor (with exception of the first node in the chain)
- have a single children (with exception of the last node in the chain)

Move filter merge after reuse

---

benchmarks/hotsoup/query_blacklist.txt
src/mir/mod.rs
src/sql/mir.rs
src/sql/mod.rs
src/sql/query_graph.rs
src/sql/reuse.rs
tests/finkelstein82.txt

Previously, we incorrectly handled `or` predicates and only allowed for one level of nested predicates. 
Now, we support multiple levels of nesting and `and` predicates are constructed by chaining the lefts-side and the right-side nodes, while `or` predicates are constructed by unioning the lefts-side and the right-side nodes.
There are limitations to the way we currently handle `or` predicates, more specifically we **don't** support:
-  `or` expressions with predicates with placeholder parameters, because these expressions are meaningless in the Soup context.
- `or` expressions with join predicates.
- `or` expressions between different tables (e.g ```table1.x = 1 OR table2.y= 42```).

Correctly handles `and` and `or` predicates

---

src/sql/mod.rs
src/sql/query_signature.rs
src/sql/reuse/finkelstein.rs
src/sql/reuse/full.rs
src/sql/reuse/helpers/mod.rs
src/sql/reuse/helpers/predicate_implication.rs
src/sql/reuse/mod.rs
src/sql/reuse/relaxed.rs
src/sql/reuse/weak.rs

Adds two reuse options other than the `Finkelstein` algorithm: `Relaxed` and `Full`. Also considers multiple reuse candidates, instead of using a scoring function to pick a single one.
- `Relaxed`: This algorithm relaxes some of the constraints in the `Finkelstein` algorithm. More specifically, it doesn't give up if a query graph is not a direct extension of an existing query graph. Instead, it tries to reuse prefixes of each query. 
- `Full`: This algorithm simply considers all query graphs as possible reuse candidates and tries to individually merge each of them into the new query being added. This should yield maximum possible reuse.
- Reuse numbers after migrating `hotsoup` until schema 66. This doesn't count reuse of base tables, queries that are an exact match, or queries that …

Add other reuse algorithm options

---

src/mir/mod.rs
src/ops/join.rs
src/sql/mir.rs
tests/finkelstein82.txt

This fixes how we handle multiple join predicates for the same pair of `(src, dst)`.
Currently, we don't support joins on multiple columns, so if we have multiple predicates, we need to create one join node per predicate.
This also fixes the issue where this [assertion](https://github.com/mit-pdos/distributary/blob/3e4c4594b971b1bc86a4bcbf676b8774522d5c6e/src/ops/join.rs#L92) was triggered when joining against the same table (by using aliases). So now we can run the following query schema:
```
CREATE TABLE r (a int, b int);
SELECT r1.a as a1, r2.a as a2 from r as r1, r as r2 where r1.a = r2.a;
SELECT r1.a as a1, r2.a as a2 from r as r1, r as r2 where r1.a = r2.b and r2.a = r1.b;
```
However, because we get rid of table aliases before node construction, we might still pick the wrong join …

Creates one join node per join predicate

---

src/flow/core/data.rs

Adds an implementation of `Debug` for `DataType` that uses the existing `Display` functionality.
This makes sure that e.g. `TinyText` is outputted as a string, instead of an array of bytes:
```
[
TinyText ("string"),
Int (10),
Int (5),
Int (1)
]
```

Use Display::fmt functionality for DataType's Debug

---

tests/lib.rs

Looks like Travis is too slow for the tests in `lib/tests.rs`. Bumping the settle time to 500 ms seems to work (re-ran the tests a few times).

Bump the settle time to get tests to pass on Travis

---

tests/lib.rs

This adds an end to end test that reads in a table and a query, runs a migration, and finally performs a few queries - all in all pretty similar to `examples/basic-recipe`. 
Context: https://github.com/mit-pdos/distributary/pull/24#issuecomment-332264030
I wanted to add a small test to the actual example as well, but couldn't find a reasonable way to do so - see https://github.com/rust-lang/cargo/issues/3559

Add basic SQL end to end test

---

benchmarks/hotsoup/hotsoup.rs
benchmarks/tpc_w/tpc_w.rs
benchmarks/vote/graph.rs
examples/basic-recipe.rs
src/flow/mod.rs
src/sql/mod.rs
src/web/sql_main.rs
tests/lib.rs
tests/mysql_comparison.rs

I've been wanting to make this change for a while now.
Since a migration mutably borrows the `Blender`, the migration usually has to happen in its own (useless) scope, at least without NLL. This is annoying. Furthermore, the requirement to call `mig.commit()` is silly since we (at least atm) cannot abort a migration.
This patch changes migrations to instead happen in a closure, which essentially wraps the same things every caller had to do previously.

Make migrations happen in a closure

---

.travis.yml
tests/lib.rs

Seems like tests like `it_works_basic` still fails on Travis sometimes with 500 ms sleep time. This adds a `SETTLE_TIME` environment variable, so that the sleep time can be increased for Travis without slowing down regular test runs.

Sleep for longer in tests only on Travis

---

Cargo.toml
README.md
examples/basic-recipe.rs

This fixes a compile error in the example from the change to `.migrate` closures (`return Err(e)` would be a return for the closure, not the entire `load_recipe` function).
Also removes `required-features = ["binaries"]` from the example to make `cargo test` check it for compile errors, and adds a small note to the README about `cargo run --example basic-recipe`.

Fix example error

---

src/ops/grouped/extremum.rs

Removes the `also test MIN` TODO comment.

Add tests for Extremum::MIN

---

Cargo.lock
Cargo.toml

Also removes the macOS comment, since that now works out of the box.

Upgrade timekeeper to 0.3.0

---

.travis.yml

This fixes the Travis build. Was released a week ago, so slightly newer than the hash that was being used before.

Use rustfmt-nightly 0.2.9

---

.travis.yml
src/flow/mutator.rs
src/sql/mir.rs
src/sql/mod.rs

Seems like pinned rustfmt versions regularly break with new nightly builds, which makes it pretty sub-optimal. This checks the codebase against HEAD of rustfmt instead. That'll probably also break from time to time, but should be easier to fix than having to update the rustfmt revision hash manually.
Another option is to just remove the check altogether - up to you!

Use HEAD of rustfmt on Travis

---

Cargo.lock
Cargo.toml
benchmarks/Cargo.toml
core/Cargo.toml
dataflow/Cargo.toml
mir/Cargo.toml
src/sql/query_graph.rs
src/tests.rs

Not sure if this is the right place to solve this, but it basically sets the column name of the output column to the alias if it exists - or `arithmetic` if it doesn't (I don't think the actual `arithmetic` name is being used for anything?).
This is sort of similar to what's done in [SqlToMirConverter.make_grouped_node](https://github.com/mit-pdos/distributary/blob/master/src/sql/mir.rs#L585-L595).

Add support for aliases in arithmetic expressions

---

Cargo.lock
Cargo.toml
core/Cargo.toml
dataflow/Cargo.toml
dataflow/src/payload.rs
dataflow/src/processing.rs
mir/Cargo.toml
src/controller/mod.rs
src/controller/sql/mod.rs
src/controller/sql/passes/implied_tables.rs
src/controller/sql/query_graph.rs
src/controller/sql/query_utils.rs

This uses `.to_string()` on nom-sql's literals and arithmetic expressions for column names. Added a rustfmt commit too for Travis, but I'll remove it if someone runs it on master before this is merged.

Use appropriate names for literals and arithmetic expressions

---

src/controller/getter.rs
src/controller/migrate/materialization/mod.rs
src/controller/mod.rs
src/controller/recipe/mod.rs
src/controller/sql/mir.rs
src/controller/sql/mod.rs
src/controller/sql/passes/implied_tables.rs
src/lib.rs
src/tests.rs
src/worker/mod.rs

A lot of these changes are in SQL/MIR which I'm not too familiar with, so I didn't want to push to master without confirmation. For the most part I just tagged functions/structs with `#[allow(unused)]` but it may be the case that many of them should be remove instead.

Re-enable unused warnings, and fix existing instances of them

---

benchmarks/vote/graph.rs
examples/basic-recipe.rs
src/controller/recipe/mod.rs
src/tests.rs

This changes the recipe syntax to allow two forms of named query:
1. `QUERY q_name: SELECT ...`
2. `q_name: SELECT ...`
The first is a *public* query, i.e., one that a client wishes to read from and for which we must maintain a leaf materialization. The second is a *shorthand*, nested query that clients won't query, but which other queries might refer to (treating it as a view/table). Only public queries receive readable leaf materializations (= reader nodes in the data flow).
Note that this is a breaking change that breaks all existing recipes. I've fixed the unit tests, the example, and "vote"; other branches need to take care when merging (@larat7 @fintelia @jonhoo @ekmartin)

Explicitly tag public queries in recipes

---

core/src/data.rs
src/tests.rs

Just thought it was annoying having to do `(i as i32).into()` in tests etc. - feel free to close if there's a good reason why it isn't implemented though!

Implement From<usize> for DataType

---

dataflow/src/node/debug.rs
dataflow/src/node/mod.rs
dataflow/src/prelude.rs
examples/basic-recipe.rs
src/controller/migrate/materialization/mod.rs
src/controller/mod.rs

The snapshotting implementation needs to know which domains have at least one materialized node, but I thought it might be useful to show it in Blender's graphviz output as well.
I'm not sure if the way I'm retrieving materialization status for a node is correct, so let me know if there's a better way to achieve the same. 
This is what it outputs for the example:
Feel free to bikeshed on how it should be shown in the output - currently it uses a half circle  for partial and a full circle for full materializations.

Materialization status in graphviz

---

channel/src/lib.rs
channel/src/tcp.rs
dataflow/src/domain/mod.rs
dataflow/src/persistence/mod.rs
src/controller/domain_handle.rs
src/controller/inner.rs
src/souplet/mod.rs

Our TcpSender/TcpReceiver supported running in a bounded mode, although this feature was almost never used. This PR removes that code

Remove window support from TCP channels

---

examples/basic-recipe.rs
src/tests.rs

Also disables partial materialization in the `basic-recipe` example, so it works until the issue has been fixed.

Add failing test for empty read before writes

---

benchmarks/vote/clients/localsoup/graph.rs
benchmarks/vote/clients/localsoup/mod.rs
benchmarks/vote/clients/netsoup.rs

Also renamed `Vote.id` to `Vote.article_id` to make things clearer. Preferably `Vote` should have `PRIMARY KEY (article_id, user)` but at the moment that crashes with a `got backfill for unnecessary key` error.

Fix column order for vote writes

---

.travis.yml
Cargo.lock
core/Cargo.toml
core/src/data.rs
core/src/lib.rs

Just two tiny `as u64` casts that were missing for the `core` tests to pass.

Fix core tests

---

dataflow/src/domain/mod.rs
dataflow/src/lib.rs
dataflow/src/node/process.rs
dataflow/src/payload.rs
dataflow/src/persistence/mod.rs
dataflow/src/prelude.rs
src/controller/mutator.rs
src/worker.rs

This makes it possible to send back more information with the ACKs than what's currently being done. An `AUTO_INCREMENT` implementation could e.g. be handled in each base operator, by returning the newly selected ID from `on_input`.
This also helps with stuff like the persistent bases implementation, where writes are persisted in `materialize` (meaning that ACKs sent from `persistence` would be premature).
Unfortunately this seems to increase write latencies with about ~10% at the 95th and 99th percentiles, which is probably just a result of the domain having to do more work (such as materializing updates) before returning an ACK. Happy to hear other suggestions for how this could be implemented too.

Send write-ACKs only after process(..) is done

---

.travis.yml
src/tests.rs

Also upgrades the nightly version on Travis - the old one has a compiler bug that has since been fixed (https://travis-ci.org/mit-pdos/distributary/builds/358092643?utm_source=github_status&utm_medium=notification).

Skip flaky shuffle tests

---

basics/src/lib.rs
basics/src/local/memory_state.rs
basics/src/local/mod.rs
basics/src/local/persistent_state.rs
basics/src/local/single_state.rs
benchmarks/vote/main.rs
dataflow/src/domain/mod.rs
dataflow/src/ops/base.rs
dataflow/src/ops/filter.rs
dataflow/src/ops/grouped/mod.rs
dataflow/src/ops/latest.rs
dataflow/src/ops/topk.rs
dataflow/src/processing.rs

Implements a `Cow`-like enum where the `Owned` branch is a `Vec<Vec<DataType>>` and `Borrowed` is a `[Row]` - this lets us avoid `Row`'s `Rc` wrapper in the `Owned` case.

Refactor LookupResult

---

README.md

This is straight forward, but makes getting up to speed less of a burden :)

Type: fix link in readme

---

Cargo.lock
noria-server/dataflow/Cargo.toml
noria-server/dataflow/src/state/persistent_state.rs

The only significant change here is that `ColumnFamily` now [has a lifetime parameter](https://github.com/rust-rocksdb/rust-rocksdb/commit/248b40b4659c4f300b46a0948b3fc175d321c397) which makes it harder to store as a part of `PersistentState`. I initially threaded through the lifetime parameter up to `PersistentState` but couldn't get past this error:
`error[E0277]: *mut librocksdb_sys::rocksdb_column_family_handle_t cannot be shared between threads safely --> noria-server/dataflow/src/state/persistent_state.rs:70:10`
`ColumnFamily` is marked as `Send` but I wonder if the way to solve this might be to mark the [inner pointer](https://github.com/rust-rocksdb/rust-rocksdb/blob/master/src/lib.rs#L288) as [`NonNull`](https://doc.rust-lang.org/std/ptr/struct.NonNull.html) in rust-rocksdb? Not …

Move back to upstream rust-rocksdb

---

noria-server/dataflow/src/lib.rs
noria-server/dataflow/src/ops/grouped/mod.rs

> A small change for a module, a big change for humanity
... Actually no 😄 , but I stumbled upon this section when trying to understand the code and I think this version is more readable. It doesn't break any tests and, according to taster doesn't appear to cause slowdown.

Factored and simplified a function out of `on_input`

---

noria-server/dataflow/src/state/keyed_state.rs
noria-server/dataflow/src/state/mk_key.rs
noria-server/dataflow/src/state/mod.rs
noria-server/dataflow/src/state/single_state.rs

The idea here is to make the conversion between `Row` (or `&[DataType]`) and an
index for the state map reusable, namely for other `State` impls.
It just so happens that that also allows me to apply some do-not-repeat-yourself
principles to the state impls using small `macro_rules`.
I did this change in preparation of implementing a custom `State`. I don't necessarily mean to suggest that this version is *better*, and *should* be merged` but I thought I'd inform you about the possibility.
The code isn't actually shorter, which I think is a bit unfortunate, but perhaps more readable.

Refactored state impl via macro and trait

---

.travis.yml

As the title suggests.
All this does is completely turn off caching on travis-ci.org.
While this significantly increases build time (~27min) it means no more timeout errors when fetching the caches.

Disable all build caches

---

Cargo.lock
noria-benchmarks/Cargo.toml
noria-benchmarks/replay/main.rs
noria-server/Cargo.toml
noria-server/dataflow/Cargo.toml
noria-server/dataflow/src/node/special/base.rs
noria-server/dataflow/src/ops/grouped/aggregate.rs
noria-server/dataflow/src/ops/grouped/concat.rs
noria-server/dataflow/src/ops/grouped/extremum.rs
noria-server/mir/Cargo.toml
noria-server/src/controller/schema.rs
noria-server/src/integration.rs
noria-server/tests/mysql_comparison.rs
noria/Cargo.toml
noria/src/data.rs
noria/src/lib.rs

This is nowhere close to be merge'able, but I thought I'd use it to get the discussion going:
While trying to see how Noria would workout on a project, I hit an issue where `unsigned BigInt(20)` column types weren't properly supported. `nom-sql` had issues parsing the SQL while trying to load it all in Noria and threw `ParseIntError { kind: Overflow }` at us. 
I started hacking trying to get something working to at least get to load the the mysql dump into noria and make progress with the testing. Now here I am… `msql-srv` seems to deal with it fine (based on my limited reading of the code), but `nom-sql` less so. I'm more than willing to make progress on this, but would love to know what y'all take is on  adding the `DataType::Unsigned(Big)Int` is. Or would it be nicer to treat these as …

Support for UnsignedInt & UnsignedBigInt

---

README.md

The text and the underlying URLs didn't match up. This fixes it now :)

Fix path typo in README

---

azure-pipelines.yml
noria-server/dataflow/Cargo.toml
noria-server/dataflow/src/lib.rs

This is work-around to enable `async-await` branch to be built on windows.
Proper fix would require fixing jemalloc build script (which is hard for msvc as jemalloc uses autoconf)

Disable jemalloc on windows to allow windows build

---

noria-server/src/worker/replica.rs

While rust-lang/rust#64445 is still a thing, we can use a type alias in a different way to make it work temporarily.

Use a type alias for FirstByte instead of boxing

---

server/dataflow/src/domain/mod.rs
server/dataflow/src/node/process.rs
server/dataflow/src/ops/union.rs
server/src/controller/migrate/materialization/mod.rs
server/src/controller/sql/passes/negation_removal.rs
server/src/controller/sql/reuse/join_order.rs

If the result of `mem::replace` is not used, it is equivalent to assignment. This way the code is more readable and doesn't give compiler warnings.
If there is an advantage to using `mem::replace`, let me know.

Replace `mem::replace` with assignment

---

noria/Cargo.toml

I think the current Tokio dependency is missing features.
I tried to compile a project depending on Noria, but I got the following error:
```
Compiling noria v0.4.1 (https://github.com/mit-pdos/noria/#770509c3)
error[E0425]: cannot find function `block_in_place` in module `tokio::task`
--> /home/jonathan/.cargo/git/checkouts/noria-8612be89bc6721f9/770509c/noria/src/channel/tcp.rs:82:26
|
82 |             tokio::task::block_in_place(f)
|                          ^^^^^^^^^^^^^^ not found in `tokio::task`
```
I looked at `noria/Cargo.toml`, which had the following Tokio dependency:
`tokio = { version = "0.2.19", features = ["net", "io-util", "sync", "time"] }`.
Based on [Tokio v0.2.19](https://docs.rs/tokio/0.2.19/tokio/task/fn.block_in_place.html),
Thus, the present PR adds the two missing …

Missing Tokio blocking features

---

noria/Cargo.toml
noria/src/channel/tcp.rs

pin-project will deprecate the project attribute due to some unfixable
limitations.
Refs: https://github.com/taiki-e/pin-project/issues/225
*Although the deprecation of the project attribute has not been released yet, this PR is submitted in advance to avoid the CI from being broken by deprecated warnings.*

Remove uses of pin_project::project attribute

---

server/dataflow/src/state/memory_state.rs
server/dataflow/src/state/persistent_state.rs

Fix a couple "variable does not need to be mutable" warnings by dropping
a couple `mut`s

Fix a couple unnecessary mutable warns

---

README.md

Not totally sure if this is the same as the original linked code. But it seemed the most similar of the code I could see.

Fix link to controller was broken with directory changes
